# ---------- Dataset settings ----------
dataset:
  path: "data/cifar10"
  drop_last: true # Drop the last batch if not full. Only effective during training.

# ---------- Model specific settings ----------
model:
  input_channels: 3
  base_channels: 32
  latent_dim: 64
